#!/bin/bash
#The purpose of this script is to run a system report to get important information about your hardware.
#This script contains inxi commands which may not be installed on all devices.
myhostname=$(hostname)
mydate=$(date)
username=$(whoami)
ram=$(inxi -m | awk '/System RAM: /{print $4,$5}')
os=$(inxi -S | awk '/Distro: /{print $6,$7,$8}')
up=$(uptime -p)
cpu=$(inxi -C |grep Info: | awk -F 'model: ' '{print $2}')
disk=$(inxi -D | awk '/ID-1: /{print $4,$5,$6,$7,$8,$9,$10}')
gpu=$(inxi -G | awk -F 'Device-1: ' '/Device-1:/ {print $2}' | cut -d ' ' -f1-4)
ip=$(hostname -I | awk '{print $1}')
gateway=$(ip r s default | awk '{print $3}')
dns=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')
users=$(who | grep seat0 | awk '{print $1}')
diskspace=$(df -h | grep '/dev/sda2' | awk '{print $1, $2}')
#use -e to show all processes running without headers
process=$(ps -e --no-headers | wc -l)
load=$(uptime | awk '{print $8,$9,$10}')
ufw=$(sudo ufw status)	
#Uses ss command to list listening ports only. uses grep to take away the local addresses
listen=$(ss -lutn | awk '/:[0-9]/{print $5}' | grep -o '[1-9][0-9]*$' | tr '\n' ' ')
cat <<EOF

System Report for $myhostname generated by $username, on $mydate
 
System Information
------------------
OS: $os
Uptime: $up
CPU: $cpu
RAM: $ram
Disk(s): $disk
Video: $gpu
Host Address: $ip
Gateway IP: $gateway
DNS Server: $dns
 
System Status
-------------
Users Logged In: $users
Disk Space: $diskspace
Process Count: $process
Load Averages: $load
Listening Network Ports: $listen
UFW Status: $ufw
EOF

